FROM grafana/grafana:latest
COPY provisioning/datasources/prometheus.yml /etc/grafana/provisioning/datasources/prometheus.yml
COPY provisioning/alerting/contactpoints.yml /etc/grafana/provisioning/alerting/contactpoints.yml
