# Generated by Django 4.2.28 on 2026-02-11 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('property_type', models.CharField(choices=[('hotel', 'Hotel'), ('boutique_hotel', 'Boutique Hotel'), ('resort', 'Resort'), ('motel', 'Motel'), ('hostel', 'Hostel'), ('bed_&_breakfast', 'Bed & Breakfast'), ('vacation_rental', 'Vacation Rental'), ('serviced_apartment', 'Serviced Apartment'), ('apart-hotel', 'Apart-Hotel'), ('villa', 'Villa'), ('guesthouse', 'Guesthouse'), ('lodge', 'Lodge'), ('other', 'Other')], max_length=30)),
                ('num_properties', models.PositiveIntegerField()),
                ('num_units', models.PositiveIntegerField()),
                ('referral_source', models.CharField(blank=True, choices=[('google_search', 'Google Search'), ('referral_/_word_of_mouth', 'Referral / Word of Mouth'), ('linkedin', 'LinkedIn'), ('facebook_/_instagram', 'Facebook / Instagram'), ('conference_/_trade_show', 'Conference / Trade Show'), ('blog_/_article', 'Blog / Article'), ('channel_partner', 'Channel Partner'), ('other', 'Other')], max_length=50)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('business_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('sole_proprietor', 'Sole Proprietor'), ('partnership', 'Partnership'), ('llc', 'LLC'), ('corporation', 'Corporation'), ('non_profit', 'Non-Profit'), ('other', 'Other')], max_length=20)),
                ('legal_business_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('business_description', models.TextField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_plan', models.CharField(choices=[('free_trial', 'Free Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free_trial', max_length=20)),
                ('subscription_status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='trialing', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending_review', max_length=20)),
                ('onboarding_step', models.CharField(choices=[('registered', 'Registered'), ('email_verified', 'Email Verified'), ('profile_completed', 'Profile Completed'), ('property_added', 'Property Added'), ('payment_configured', 'Payment Configured'), ('onboarding_complete', 'Onboarding Complete')], default='registered', max_length=30)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('profile_photo', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hosts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Host Profile',
                'verbose_name_plural': 'Host Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
